server:
  port: 8083
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: libOnboardingCart
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
logging:
  level:
    root: INFO
    org:
      hibernate: WARN
      hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE

flyway:
  enabled: true
  out-of-order: true
  locations: classpath:db/migration/oracle
